import type { SharkmoState } from "@/lib/sharkmo/types";

const now = Date.now();
const daysAgo = (days: number) => new Date(now - days * 24 * 60 * 60 * 1000).toISOString();
const daysFromNow = (days: number) => new Date(now + days * 24 * 60 * 60 * 1000).toISOString();

export const sharkmoInitialState: SharkmoState = {
  contents: [
    {
      id: "content-keepmoving-manifesto",
      title: "KeepMoving Manifesto",
      description: "Reel manifesto sul movimento come identita Sharkmo.",
      category: "Filosofia / Messaggi",
      pillar: "Movimento",
      platform: "Instagram / TikTok",
      format: "Reel",
      status: "Editato",
      hook: "La maggior parte delle persone aspetta il momento giusto. Lo squalo no.",
      scriptText: "Non aspettare di sentirti pronto. Muoviti, correggi, continua.",
      visualNotes: "Tagli rapidi, nero/bordeaux, dettagli oro, camminata notturna.",
      cta: "KeepMoving.",
      source: "Brand manifesto",
      publishDate: null,
      createdAt: daysAgo(9),
      updatedAt: daysAgo(2),
      lastStatusChangeAt: daysAgo(2),
      linkedPhilosophyConceptId: "philosophy-movimento-continuo",
      notes: "Pronto per programmazione.",
    },
    {
      id: "content-anti-burattino",
      title: "Anti-burattino",
      description: "Script breve su indipendenza mentale e scelta della propria direzione.",
      category: "Filosofia / Messaggi",
      pillar: "Anti-burattino",
      platform: "TikTok",
      format: "Short talking head",
      status: "Script",
      hook: "Se non scegli tu la direzione, qualcuno la sceglie per te.",
      scriptText: "La liberta non e fare tutto. E sapere cosa non ti muove piu.",
      visualNotes: "Close-up, luce dura, sfondo scuro.",
      cta: "Smetti di farti muovere.",
      source: "Nota filosofia",
      publishDate: null,
      createdAt: daysAgo(7),
      updatedAt: daysAgo(6),
      lastStatusChangeAt: daysAgo(6),
      linkedPhilosophyConceptId: "philosophy-anti-burattino",
      notes: "Da portare a registrazione.",
    },
    {
      id: "content-jeans-bts",
      title: "Jeans Sharkmo BTS",
      description: "Dietro le quinte del primo jeans e dei dettagli oro/bordeaux.",
      category: "Dietro le quinte",
      pillar: "Costruzione del brand",
      platform: "Instagram",
      format: "Reel BTS",
      status: "Da editare",
      hook: "Un capo non nasce dal nulla. Nasce da decisioni piccole e ossessive.",
      scriptText: "",
      visualNotes: "Mockup, rivetti, patch, sketch.",
      cta: "Segui la costruzione.",
      source: "Product Lab",
      publishDate: null,
      createdAt: daysAgo(5),
      updatedAt: daysAgo(4),
      lastStatusChangeAt: daysAgo(4),
      linkedProductId: "product-jeans-v1",
      notes: "Materiale registrato, serve editing.",
    },
  ],
  products: [
    {
      id: "product-jeans-v1",
      name: "Jeans Sharkmo V1",
      category: "Jeans",
      status: "Tech pack in corso",
      previewImageUrl: "",
      concept: "Jeans nero premium con dettagli oro e patch rossa Sharkmo.",
      target: "Drop founder, pubblico street/luxury.",
      useCase: "Outfit hero, contenuti BTS, primo capo identitario.",
      colors: "nero, oro, bordeaux",
      materials: "denim pesante, rivetti oro, patch rossa",
      fit: "straight relaxed",
      designDetails: "rivetti stella oro, patch rossa, cuciture oro",
      logoPlacement: "retro waist patch e piccolo dettaglio tasca",
      patchDetails: "patch bordeaux con emboss Sharkmo",
      accessories: "zip metallo scuro, bottone oro",
      techPackStatus: "In corso",
      techPackFileUrl: "",
      mockupFiles: ["mockup-jeans-v1.png"],
      referenceImages: ["reference-denim-black.png"],
      notes: "Manca dettaglio materiali e misure base.",
      nextAction: "Completa materiali e misure tech pack.",
      createdAt: daysAgo(14),
      updatedAt: daysAgo(8),
      lastStatusChangeAt: daysAgo(10),
    },
    {
      id: "product-felpa-chrome",
      name: "Felpa Sharkmo Chrome",
      category: "Felpa",
      status: "Mockup",
      previewImageUrl: "",
      concept: "Felpa scura con logo chrome e taglio premium.",
      target: "Secondo capo visual, forte per contenuti outfit.",
      useCase: "Drop autunno, shooting notturno.",
      colors: "grigio scuro, cromato, nero",
      materials: "cotone pesante, stampa chrome",
      fit: "boxy",
      designDetails: "logo grande frontale, dettagli su maniche",
      logoPlacement: "petto centrale",
      patchDetails: "micro patch laterale",
      accessories: "cordini neri con punta metallica",
      techPackStatus: "Mancante",
      techPackFileUrl: "",
      mockupFiles: ["mockup-hoodie-chrome.png"],
      referenceImages: [],
      notes: "Serve validare silhouette.",
      nextAction: "Definire fit e dettagli design.",
      createdAt: daysAgo(8),
      updatedAt: daysAgo(3),
      lastStatusChangeAt: daysAgo(3),
    },
  ],
  concepts: [
    {
      id: "philosophy-movimento-continuo",
      title: "Movimento continuo",
      description: "Lo squalo vive muovendosi: disciplina, azione, correzione.",
      type: "Argomento",
      pillar: "Movimento",
      source: "Manifesto Sharkmo",
      quote: "Non aspettare di sentirti pronto. Muoviti.",
      sharkmoMeaning: "Lo squalo vive muovendosi. Il brand premia direzione, azione e adattamento.",
      possibleContentIdea: "Reel motivazionale KeepMoving.",
      possibleProductIdea: "Drop KeepMoving.",
      status: "Pronto per script",
      createdAt: daysAgo(11),
      updatedAt: daysAgo(5),
    },
    {
      id: "philosophy-anti-burattino",
      title: "Anti-burattino",
      description: "Scegliere la propria direzione invece di farsi guidare dalla societa.",
      type: "Concetto psicologico",
      pillar: "Anti-burattino",
      source: "Riflessione personale",
      quote: "Se non scegli tu, qualcuno sceglie per te.",
      sharkmoMeaning: "Indipendenza mentale, identita, consapevolezza dello status game.",
      possibleContentIdea: "Short sul non farsi muovere.",
      possibleProductIdea: "Grafica capsule anti-burattino.",
      status: "Da sviluppare",
      createdAt: daysAgo(9),
      updatedAt: daysAgo(7),
    },
  ],
  performances: [
    {
      id: "performance-old-bts",
      contentItemId: "content-old-bts",
      platform: "Instagram",
      publishedAt: daysAgo(10),
      views: 1850,
      likes: 122,
      comments: 9,
      shares: 13,
      saves: 24,
      followersGained: 18,
      averageWatchTime: "7.4s",
      retention: "41%",
      notes: "Buon interesse sui dettagli prodotto.",
      whatWorked: "Dettagli ravvicinati, testo breve.",
      whatToImprove: "CTA piu diretta.",
      finalJudgement: "Da replicare con piu ritmo.",
      createdAt: daysAgo(9),
      updatedAt: daysAgo(8),
    },
  ],
  dailyPriorities: [],
  events: [
    {
      id: "event-content-edited",
      type: "CONTENT_EDITED",
      area: "Content Studio",
      entityType: "content",
      entityId: "content-keepmoving-manifesto",
      title: "Contenuto editato",
      description: "KeepMoving Manifesto e pronto per programmazione.",
      fromStatus: "Da editare",
      toStatus: "Editato",
      createdAt: daysAgo(2),
    },
    {
      id: "event-content-recorded",
      type: "CONTENT_RECORDED",
      area: "Content Studio",
      entityType: "content",
      entityId: "content-jeans-bts",
      title: "Contenuto registrato",
      description: "Registrato BTS Jeans Sharkmo V1.",
      fromStatus: "Da registrare",
      toStatus: "Registrato",
      createdAt: daysAgo(5),
    },
    {
      id: "event-product-advanced",
      type: "PRODUCT_ADVANCED",
      area: "Product Lab",
      entityType: "product",
      entityId: "product-jeans-v1",
      title: "Prodotto avanzato",
      description: "Jeans Sharkmo V1 passato a Tech pack in corso.",
      fromStatus: "Mockup",
      toStatus: "Tech pack in corso",
      createdAt: daysAgo(10),
    },
    {
      id: "event-performance-updated",
      type: "PERFORMANCE_UPDATED",
      area: "Performance",
      entityType: "performance",
      entityId: "performance-old-bts",
      title: "Performance aggiornata",
      description: "Aggiornate metriche contenuto BTS.",
      createdAt: daysAgo(8),
    },
    {
      id: "event-previous-published",
      type: "CONTENT_PUBLISHED",
      area: "Content Studio",
      entityType: "content",
      entityId: "content-old-bts",
      title: "Contenuto pubblicato",
      description: "BTS prodotto pubblicato.",
      createdAt: daysAgo(10),
    },
  ],
};
